### ISSUE TITLE
query params will get escaped accidentally

### ISSUE THREAD

**Issue by zetachang** [jrmdayn/googleapis-batcher#13]
First of all, thank you for building this amazing tool.

I am trying with some Google API, and I realized if the request path contains query params (e.g. `?format=metadata`), it will get escaped by the Handlebars template at this line https://github.com/jrmdayn/googleapis-batcher/blob/45f73fe317638556c88183745ebf11a438666179/src/makeMultipartMixedRequest/handlebarsTemplates.ts#L16

which will result in a request failure.

My temporary fix is changing `{{path}}` to `{{{path}}}`, but I am not an expert of Handlebars, so not sure if this has any side effect, but this change did fix my issue.

**Comment by jrmdayn** [comment]
Thanks @zetachang for bringing this up. I've publish v0.7.0, could you give it a try and let me know if it helps?

**Comment by zetachang** [comment]
thank you @jrmdayn , works fine for me 👍
